-- DDL: Create core Oracle tables for ERP mode
-- File: db/ddl/01_create_tables.sql
-- Conventions: CHAR(1) for booleans ('T'/'F'), DATE for dates, NUMBER for ids, VARCHAR2 for text
-- No triggers/procedures in this file. No foreign keys (will add later per instruction).

PROMPT "Creating EMP_MASTER..."

CREATE TABLE EMP_MASTER (
  EMP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID VARCHAR2(64),
  EMPLOYEE_ID VARCHAR2(64) NOT NULL,
  EMPNO VARCHAR2(50),
  EMPNAME VARCHAR2(255),
  FULL_NAME VARCHAR2(255),
  COMPANY_ID VARCHAR2(64),
  BRANCH_ID VARCHAR2(64),
  BIOMETRIC_ID VARCHAR2(64),
  ERP_USERNAME VARCHAR2(100),
  API_USERNAME VARCHAR2(100),
  IS_ACTIVE CHAR(1) DEFAULT 'T' NOT NULL,
  INACTIVE_DATE DATE,
  CANCEL CHAR(1) DEFAULT 'F' NOT NULL,
  CREATEDON DATE DEFAULT SYSDATE,
  CREATEDBY VARCHAR2(128),
  MODIFIEDON DATE,
  MODIFIEDBY VARCHAR2(128)
);

-- Optional: index EMPNO for lookups
CREATE INDEX IDX_EMP_MASTER_EMPNO ON EMP_MASTER (EMPNO);
CREATE INDEX IDX_EMP_MASTER_ERP_USERNAME ON EMP_MASTER (ERP_USERNAME);

PROMPT "Creating API_LINK_MASTER..."

CREATE TABLE API_LINK_MASTER (
  API_LINK_MASTER_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  LINKDATE DATE DEFAULT SYSDATE NOT NULL,
  LINKNO VARCHAR2(128),
  ERPUSERNAME VARCHAR2(100) NOT NULL,
  APIUSERNAME VARCHAR2(100),
  EMPNAME VARCHAR2(255),
  APPLICABLEFROM DATE,
  APPLICABLETO DATE,
  ACTIVE CHAR(1) DEFAULT 'T' NOT NULL,
  CANCEL CHAR(1) DEFAULT 'F' NOT NULL,
  CREATEDON DATE DEFAULT SYSDATE,
  CREATEDBY VARCHAR2(128),
  MODIFIEDON DATE,
  MODIFIEDBY VARCHAR2(128)
);

-- Enforce numeric APIUSERNAME when present
ALTER TABLE API_LINK_MASTER ADD CONSTRAINT CHK_API_LINK_MASTER_APIUSERNAME_NUM CHECK (APIUSERNAME IS NULL OR REGEXP_LIKE(APIUSERNAME, '^[0-9]+$'));

-- Enforce uniqueness for ACTIVE ERPUSERNAME (only one active mapping per ERPUSERNAME)
-- Achieved via function-based unique index: only ERPUSERNAME values for active & not-cancel rows are indexed
CREATE UNIQUE INDEX UX_API_LINK_MASTER_ERP_ACTIVE ON API_LINK_MASTER (CASE WHEN ACTIVE='T' AND CANCEL<>'T' THEN ERPUSERNAME ELSE NULL END);

-- Indexes for common lookups
CREATE INDEX IDX_API_LINK_MASTER_ERP ON API_LINK_MASTER (ERPUSERNAME);
CREATE INDEX IDX_API_LINK_MASTER_API ON API_LINK_MASTER (APIUSERNAME);

PROMPT "Creating USER_ROLES..."

CREATE TABLE USER_ROLES (
  USER_ROLE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  USER_ID VARCHAR2(64) NOT NULL,
  ROLE VARCHAR2(64) NOT NULL,
  CREATEDON DATE DEFAULT SYSDATE
);

CREATE INDEX IDX_USER_ROLES_USER ON USER_ROLES (USER_ID);
CREATE UNIQUE INDEX UX_USER_ROLES_USER_ROLE ON USER_ROLES (USER_ID, ROLE);

PROMPT "Creating skeleton ATTENDANCE_PUNCHES..."

CREATE TABLE ATTENDANCE_PUNCHES (
  PUNCH_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PROFILE_ID NUMBER,
  PUNCH_TIME DATE,
  PUNCH_TYPE VARCHAR2(64),
  CREATEDON DATE DEFAULT SYSDATE
);

CREATE INDEX IDX_ATT_PUNCH_PROFILE ON ATTENDANCE_PUNCHES (PROFILE_ID);

-- Assumptions:
-- 1) Use 'T'/'F' for all CHAR(1) flags (IS_ACTIVE, ACTIVE, CANCEL).
-- 2) Primary keys use IDENTITY to avoid triggers at this stage.
-- 3) Partial-unique behavior (one active mapping per ERPUSERNAME) enforced via function-based unique index above.
-- 4) No foreign key constraints are created yet (per instruction). We will add them after schema sign-off.

PROMPT "DDL creation file completed: db/ddl/01_create_tables.sql"
